/*
 *  Generated by scripts/30-deploy.sh at deploy time; the placeholder is what
 *  ships if built without the script. Lets a log identify its exact build.
 */
#pragma once
#define KODI_PS5_BUILD_STAMP "unknown"
