#!/usr/bin/env python3
# Generate a C export table from a list of symbol names (one per line): the
# {name, address} pairs the binary-add-on loader's resolver scans to bind an
# add-on's C/C++ runtime imports to the eboot's own copies.
#
# Hard-won shape, each constraint proven by bisection against the FSELF
# converter (ps5-native-tool), which segfaults on:
#   - a static array of absolute symbol pointers (.quad symbol / &symbol as
#     data): materialises a null-initialised GOT/pointer slot the converter
#     walks and calls through -> crash (call *(%rbx), rbx=0); and
#   - any object adding an __attribute__((constructor)) / .init_array entry.
# A 1 KB blob in the same link slot converts fine (PADTEST), so it is the
# symbol *address-takes as data*, not the object or its size.
#
# Therefore: no constructor, and addresses are loaded at run time through a
# GOTPCREL *code* reference (leaq sym@GOTPCREL(%rip)), the same relocation the
# rest of the eboot uses for every extern call - which the converter handles.
# The table lives in .bss and is filled by kodi_addon_import_fill(), called
# once by the resolver (HostExports.cpp). The link still fails on a missing
# symbol (its GOT entry is referenced), keeping the presence check.
import sys

names = [l.strip() for l in sys.stdin if l.strip() and not l.startswith('#')]
names = sorted(set(names))

out = []
out.append('/* generated by ps5-gen-addon-exports.py - do not edit */')
out.append('struct HE { const char* name; void* addr; };')
out.append('')
for i, n in enumerate(names):
    esc = n.replace('\\', '\\\\').replace('"', '\\"')
    out.append(f'static const char name_{i}[] = "{esc}";')
out.append('')
out.append(f'struct HE kodi_addon_import_table[{len(names) + 1}];')
out.append(f'unsigned long kodi_addon_import_count = {len(names)};')
out.append('')
out.append('/* Not a constructor: the resolver calls this once on first use. Each')
out.append(' * address is read from the symbol\'s GOT entry via a PC-relative code')
out.append(' * reference, so no static data relocation (and no null pointer slot for')
out.append(' * the converter to trip on) is created. */')
out.append('void kodi_addon_import_fill(void)')
out.append('{')
for i, n in enumerate(names):
    out.append(f'  kodi_addon_import_table[{i}].name = name_{i};')
    out.append('  {')
    out.append('    void* a;')
    out.append(f'    __asm__("leaq {n}@GOTPCREL(%%rip), %0" : "=r"(a));')
    out.append(f'    kodi_addon_import_table[{i}].addr = *(void**)a;')
    out.append('  }')
out.append(f'  kodi_addon_import_table[{len(names)}].name = 0;')
out.append(f'  kodi_addon_import_table[{len(names)}].addr = 0;')
out.append('}')
sys.stdout.write('\n'.join(out) + '\n')
